steps:
  - name: 'alpine:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk update && \
        apk add openjdk11 imagemagick ffmpeg mediainfo perl-image-exiftool libwebp curl && \
        echo "Installed packages:" && \
        apk info | grep -E 'openjdk|imagemagick|ffmpeg|mediainfo|perl-image-exiftool|libwebp'

  - name: 'gcr.io/contribly-dev/scala-sbt'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        sbt clean docker:publishLocal

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'eu.gcr.io/contribly-dev/media-monkey:$COMMIT_SHA'
      - 'eu.gcr.io/contribly-dev/media-monkey:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'eu.gcr.io/contribly-dev/media-monkey:$COMMIT_SHA'
