steps:
  - name: 'gcr.io/contribly-dev/scala-sbt'
    args: ['clean', 'docker:publishLocal']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'eu.gcr.io/contribly-dev/media-monkey:$COMMIT_SHA'
      - 'eu.gcr.io/contribly-dev/media-monkey:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'eu.gcr.io/contribly-dev/media-monkey:$COMMIT_SHA'