steps:
- name: 'gcr.io/$PROJECT_ID/scala-sbt'
  args: ['update', 'clean', 'docker:publishLocal']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '-t', 'media-monkey:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'media-monkey:$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/media-monkey:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/media-monkey:$COMMIT_SHA']
