steps:
- name: 'gcr.io/contribly-dev/scala-sbt'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "SBT Version Installed:" && \
      sbt sbtVersion

- name: 'debian:buster'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && \
      apt-get install -y curl openjdk-11-jre-headless imagemagick ffmpeg mediainfo libimage-exiftool-perl webp && \
      echo "Installed packages:" && \
      dpkg -l | grep -E 'openjdk|imagemagick|ffmpeg|mediainfo|libimage-exiftool-perl|webp'

- name: 'gcr.io/cloud-builders/docker'
  args: ['images']  # Debug step to list Docker images

- name: 'gcr.io/contribly-dev/scala-sbt'
  args: ['clean', 'docker:publishLocal']

- name: 'gcr.io/cloud-builders/docker'
  args: ['images']  # Debug step to list Docker images

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - 'eu.gcr.io/contribly-dev/media-monkey:$COMMIT_SHA'
    - 'eu.gcr.io/contribly-dev/media-monkey:$COMMIT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  args: ['images']  # Debug step to list Docker images

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'eu.gcr.io/contribly-dev/media-monkey:$COMMIT_SHA'
