# Use the Debian Buster base image
FROM debian:buster

# Set the working directory
WORKDIR /app

# Update and install required packages
RUN apt-get update -y && \
    apt-get install -y curl && \
    apt-get install -y openjdk-11-jre-headless imagemagick ffmpeg mediainfo libimage-exiftool-perl webp && \
    apt-get clean

# Install sbt
ARG SBT_VERSION=1.3.5
RUN curl -L -o sbt-$SBT_VERSION.deb https://repo.scala-sbt.org/scalasbt/debian/sbt-$SBT_VERSION.deb && \
    dpkg -i sbt-$SBT_VERSION.deb && \
    rm sbt-$SBT_VERSION.deb

# Prevent this error: java.lang.IllegalStateException: cannot run sbt from root directory without -Dsbt.rootdir=true
ENV SBT_ROOTDIR=true

# Copy the project files
COPY . .

# Build the project
RUN sbt compile

# Set the entry point (if needed, update this to your application's main class)
# CMD ["sbt", "run"]

