apiVersion: v1
kind: Service
metadata:
  name: media-monkey
spec:
  type: NodePort
  selector:
    app: media-monkey
  ports:
  - port: 9001
    nodePort: 32001
    name: media-monkey
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: media-monkey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: media-monkey
    spec:
      containers:
      - name: media-monkey
        image: localhost:5000/media-monkey:1.0
        ports:
        - containerPort: 9001
      - name: apache-tika
        image: localhost:5000/apache-tika:1.11
        ports:
        - containerPort: 9998
